config/routes.rb
Usefulapp::Application.routes.draw do

  resources :locations
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]

  root 'locations#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
	attr_accessible :address, :latitude, :longitude
	geocoded_by :address
	after_validation :geocode, :if => :address_changed?
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base

  include BCrypt

attr_accessible :name, :email, :password, :password_digest 

validates_presence_of :email, :password

  # def password
  #   @password
  # end

  def password
    @password ||= Password.new(password_digest)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_digest = @password
  end

  # def password=(new_password)
  #   @password = new_password
  #   self.password_digest = BCrypt::Password.create(new_password)
  # end


  def authenticate(login_password)
    if BCrypt::Password.new(self.password_digest) == login_password
    self
  else
    false
  end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

before_action :authenticate_user
before_action :set_location, only: [:edit, :update, :show, :destroy]

def index
		@locations = Location.all
	end

	def show
  		@location = Location.find(params[:id])
  	end

	def new
		@location = Location.new
	end

	def create
		location_params()
		@location = Location.new
		@location = Location.new(location_params)
		if @location.save
			redirect_to locations_path
		else
			render 'new'
		end
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		if @location.update(location_params)
			redirect_to locations_path(@location)
		else
			render 'edit'
		end
	end

	def destroy
		@location = Location.find(params[:id])
		@location.destroy
		redirect_to locations_path
	end


	def location_params
		params.require(:location).permit(:name, :address, :store_type)
	end

	def set_location
		@location = Location.find(params[:id])
	end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

     def new
     end

     def create 
           @user = User.where(:email => params[:session][:email]).first
               if @user == nil || !@user.authenticate(params[:session][:password])
                    flash[:error] = "invalid email address"
                    render 'new'
               else
                    session[:remember_token] = @user.id.to_s
                    @current_user = @user
                    redirect_to root_path
               end
     end

     def destroy
          session.delete(:remember_token)
          redirect_to root_path
     end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user=User.new(user_params)
		if @user.save
			flash[:success] = "Your account has been saved"
			redirect_to :root
		else
			render 'new'
		end
	end 

	private

	def user_params
		params.require(:user).permit(:name, :email, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
		if session[:remember_token] 
			@current_user ||= User.find(session[:remember_token])
		else
			@current_user = nil
		end
	end

	def authenticate_user
		if !self.current_user
			redirect_to new_session_path
		end
	end


end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Usefulapp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |l| %>

	<h2>Name: <%= l.text_field :name, class: "form-control" %></h2>
	<h2>Address: <%= l.text_field :address, class: "form-control" %></h2>
	<h2>Store Type: <%= l.text_field :store_type, class: "form-control" %></h2>
	<%= l.submit "Save location", class: "btn" %>
<% end %>

app/views/locations/edit.html.erb
<h1><b>Location Detail Page</b></h1>
<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4 border">	
				<%= render 'form' %>
			
				<%= link_to " ", @location, {method: :delete, data: {confirm: "Delete this location?"}, class: "glyphicon glyphicon-trash show-link"} %>

				<%= link_to "Back", locations_path, class: "show-link"%>
			</div>
			<div class="col-md-4"></div>
</div>

app/views/locations/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>


<h1><b>Locations Page</b></h1>
<div class="row">
	
		<% @locations.each do |l| %>
				<div class="panel panel-default">	
					<h4>Name: <%= l.name %></h4>
					<h4> Address: <%= l.address %></h4>
					<h4> Store Type: <%= l.store_type %></h4>
          <h4> Longitude: <%= l.longitude %></h4>
          <h4> Latitude: <%= l.latitude %></h4>

					<%= link_to "Show Location", location_path(l), class: "btn btn-danger" %>
				</div>
		<% end %>

    <div style='width: 800px;'>

      <div id="directions" style='width: 800px; height: 400px;'></div>

    </div>	

</div>

<h4><%= link_to "Add a new location", new_location_path %></h4>

<script type="text/javascript">
  var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();

function calcRoute() {
  // start with the first location
  var origin      = new google.maps.LatLng(<%= @locations.first.latitude %>, <%= @locations.first.longitude %>);
  var waypts = [];

  // add a waypoint for each location
  //    starting with the second location, and repeating until the second to last location
  // if there are only 2 locations, the for loop will end
  <% for x in 1..(@locations.length-2) %>

  var waypt = new google.maps.LatLng(<%= @locations[x].latitude %>, <%= @locations[x].longitude %>);
  waypts.push({
          location:waypt,
          stopover:true});
  
  <% end %>

  var destination = new google.maps.LatLng(<%= @locations.last.latitude %>, <%= @locations.last.longitude %>);
  var request = {
      origin:      origin,
      destination: destination,
      waypoints: waypts,
      travelMode:  google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    }
  });
}

calcRoute();

var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'directions'}}, function(){
  directionsDisplay.setMap(handler.getMap());
});
 </script>

app/views/locations/new.html.erb
<h1>New Location</h1>

<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4 border">

				<%= render 'form' %>
				<%= link_to "Back to location list", locations_path %>
			
			</div>
			<div class="col-md-4"></div>
</div>

app/views/locations/show.html.erb
<h1><b>Location Detail Page</b></h1>
<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4 border">	
				<h2>Name: <%= @location.name %></h2>
				<h2>Address: <%= @location.address %></h2>
				<h3>Store Type: <%= @location.store_type %></h3>
				<h3> Longitude: <%= @location.longitude %></h3>
          		<h3> Latitude: <%= @location.latitude %></h3>
				<%= link_to " ", edit_location_path(@location), class: "glyphicon glyphicon-pencil show-link" %>
			
				<%= link_to " ", @location, {method: :delete, data: {confirm: "Delete this location?"}, class: "glyphicon glyphicon-trash show-link"} %>

				<%= link_to "Back", locations_path, class: "show-link"%>
			</div>
			<div class="col-md-4"></div>
</div>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<div class="row">
			<div class="col-md-4"></div>
			<div class="col-md-4 border tall">

				<%= form_for @user do |f| %>

					<h2>Name: <%= f.text_field :name, class: "form-control" %></h2>
					<h2>Email: <%= f.text_field :email, class: "form-control" %></h2>
					<h2>Password: <%= f.password_field :password, class: "form-control" %></h2>
					<%= f.submit "Sign up", class: "btn btn-primary" %>
				<% end %>
			<%= link_to "Sign In", new_session_path, class: "btn btn-success" %>
			</div>
			<div class="col-md-4"></div>
</div>